language: node_js
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
node_js:
  - '6.1'
before_script:
  - 'npm install bulk-decaffeinate'
  - 'git clone --depth 1 https://github.com/codecombat/codecombat.git'
